// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXycATx1KlajsUNX_81Yt15uiDXgT8ms',
    appId: '1:234798625942:web:c5ad532095fb9d0ebe3eb7',
    messagingSenderId: '234798625942',
    projectId: 'flutter-auth-app-10ab4',
    authDomain: 'flutter-auth-app-10ab4.firebaseapp.com',
    storageBucket: 'flutter-auth-app-10ab4.firebasestorage.app',
    measurementId: 'G-K561BV1L82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcT6k64XpSUFMYUjpJJ0c1jWDVKi9lKvc',
    appId: '1:234798625942:android:c755cc7bce607ff2be3eb7',
    messagingSenderId: '234798625942',
    projectId: 'flutter-auth-app-10ab4',
    storageBucket: 'flutter-auth-app-10ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnR3ETEc5CERTtxT8hx1yp2Vo9nKvurE8',
    appId: '1:234798625942:ios:4f4388129b8b69a8be3eb7',
    messagingSenderId: '234798625942',
    projectId: 'flutter-auth-app-10ab4',
    storageBucket: 'flutter-auth-app-10ab4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationApp',
  );
}
